spring.datasource.url=jdbc:postgresql://localhost:5432/delivery
spring.datasource.username=postgres
spring.datasource.password=Massa1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true